project:
  type: website
  render:
    - "*.ipynb"
    - "!mdsample.qmd"
    - "!samples/"

website:
  title: "Quarto"
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - auto: "*.ipynb"

format:
  html:
    toc: true
    css: styles.css
    code-block-bg: true
