project:
  type: website

website:
  title: "Quarto"
  sidebar:
    style: "docked"
    search: true
    contents:
      - auto: "*.ipynb"

format:
  html:
    toc: true
    css: styles.css
    code-block-bg: true
